# Generated by Django 5.0.7 on 2024-08-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_status_alter_productreview_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default='default2.jpg', upload_to='category_images/'),
        ),
    ]
